### ISSUE TITLE
Setup guide Needed.

### ISSUE THREAD

**Issue by FevLoad** [PowerModder/Watchdog-Adult-Renamer#3]
Hello there, I'm interesting in this script and I would like to get it work on my machine,
but I have few question.

- Does it have to be on the same machne that plex server running on?
- what exactly I need to do I followed your guide on the Readme 
but still got error message when I run ` pip install -r requirements.txt`

the ERROR is  the follwoing:- 

------------------------------------
 ```ERROR: Command errored out with exit status 1:
     command: /usr/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-nEIfoK/pyenchant/setup.py'"'"'; __file__='"'"'/tmp/pip-install-nEIfoK/pyenchant/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-nEIfoK/pyenchant/pip-egg-info
         cwd: /tmp/pip-install-nEIfoK/pyenchant/
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-nEIfoK/pyenchant/setup.py", line 212, in <module>
        import enchant
      File "enchant/__init__.py", line 92, in <module>
        from enchant import _enchant as _e
      File "enchant/_enchant.py", line 145, in <module>
        raise ImportError(msg)
    ImportError: The 'enchant' C library was not found. Please install it via your OS package manager, or use a pre-built binary wheel from PyPI.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.```

**Comment by PowerModder** [comment]
Hello and happy new year.
Yes the documentation is far behind due to personal time.
As i can see from the directory you are trying to install the requirements to a Linux distro? I didn't test it on other OS other than Windows. The problem is the pip install pyenchant package.
I have found this that maybe can solve your problem
https://stackoverflow.com/questions/21083059/enchant-c-library-not-found-while-installing-pyenchant-using-pip-on-osx
As for where the script-program can run. It can run anywhere if you have the requirements installed (python and the packages)!!! 
I don't know what your setup is or what you can/want to do but i can present you some use cases.

First you make three directories. One that the program will watch for changes, one that the program will move matched files and one that the program will move unmatched files. Let's call those directories WatcherPath, RestPath and Unmatched For example.
F:\Renamer\Watcher Paths
F:\Renamer\Rest Paths
F:\Renamer\Unmatched

Inside the WatcherPath you **should** make a folder structure similar to your Plex library. For example I have a directory that Plex uses for which inside there i have sub-directories for each site
G:\XXX\2D (Main directory)
G:\XXX\2D\Brazzers (sub-directory for Brazzers)
G:\XXX\2D\Naughty America (sub-directory for Naughty America)

You should have sub-directories like Naughty America, Brazzers at your Watcher Path too! You can use Useful-Scripts/CloneDir.py to make an absolute 'clone' of the directories that you have in G:\XXX\2D to  F:\Renamer\Watcher Paths. So you end up with:
F:\Renamer\Watcher Paths\Brazzers
F:\Renamer\Watcher Paths\Naughty America

Rest Path and Unmatched can be an empty folder-directory. Don't bother.

Then you are enabling the program, you set your directories through the UI, set a strip symbol if you prefer ID over scene title or if you want to just do a dry-run 'test' without moving the files from the Watcher Path in case of matched or unmatched. You click set preferences and start watchdog.
Let's say you download a Brazzers scene. You just drag and drop it to
F:\Renamer\Watcher Paths\Brazzers
Program will see a new file and see that you dropped it inside the Brazzers sub-folder so it knows it is a Brazzers scene. Then it will use the search_function to match the filename that you dropped to a scene. If it succesful then it will rename and move the file to 
F:\Renamer\Rest Paths\Brazzers . It will automatically create the sub-directory for the site in the Rest path. It also creates log per scene/file so you can see if the scene was matched correctly. Bare in mind that can be a mismatch especially if you are using title matching. I personally use sceneID matching wherever is possible because it is a '1-1' match so sites like Brazzers end up with a scene name: Brazzers - 3789731 ~ Xander Corvus & Romi Rain - ZZ Series . I use a strip symbol of ~  using PhoenixAdult metadata agent. If you don't know what it is then don't use it. The scene name will be: Brazzers - 3789731 but again this is a personal preference to have Actors and Subsites to my filename so i can search it through my disk.
If you download the scene through Web Browser you can download it directly to the watcher path/site sub-directory.
Then you can just take the whole RestPath directory and Cut/paste it to your Plex Library folder.
If you all confident that there will be no mismatching of your scene the Rest Path can be your Plex Library Folder.
I personally have a directory that plex uses as a library to see if my new content is correctly matching. If it is then i just move the files to the main directory.
For now the program is using the sub-folders of the Watcher Path to determine the site that needs to use to do the matching. I don't think i will change that because if you download content officially let's say from Brazzers the name of the file is scene-title_quality so there is no way to say to the program 'you know this is a brazzers scene. Do the matching with brazzers'. Unofficially content have names like brazzers_scenedate_scenetitle_actor_kleenex into their filename so you can extract from what site it is.
If still you have questions please let me know.

**Comment by PowerModder** [comment]
I will be off for like 1 month just to let you know.

**Comment by FevLoad** [comment]
I'll test it on windows tonight.
